---
apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: publish-codescannerfossa
spec:
  resource:
    kind: CodeScannerFossa
    apiGroup: maintainer-d.cncf.io
    version: v1alpha1
  related:
    - identifier: "configmap-with-code-scanner-config"
      origin: service
      kind: ConfigMap
      reference:
        name:
          path: spec.configMapName
---
apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: publish-codescannersnyk
spec:
  resource:
    kind: CodeScannerSnyk
    apiGroup: maintainer-d.cncf.io
    version: v1alpha1
  related:
    - identifier: "configmap-with-code-scanner-config"
      origin: service
      kind: ConfigMap
      reference:
        name:
          path: spec.configMapName
